# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnsureContainer = channel.unary_unary(
                '/esb.agent.v1.AgentService/EnsureContainer',
                request_serializer=agent__pb2.EnsureContainerRequest.SerializeToString,
                response_deserializer=agent__pb2.WorkerInfo.FromString,
                _registered_method=True)
        self.DestroyContainer = channel.unary_unary(
                '/esb.agent.v1.AgentService/DestroyContainer',
                request_serializer=agent__pb2.DestroyContainerRequest.SerializeToString,
                response_deserializer=agent__pb2.DestroyContainerResponse.FromString,
                _registered_method=True)
        self.PauseContainer = channel.unary_unary(
                '/esb.agent.v1.AgentService/PauseContainer',
                request_serializer=agent__pb2.PauseContainerRequest.SerializeToString,
                response_deserializer=agent__pb2.PauseContainerResponse.FromString,
                _registered_method=True)
        self.ResumeContainer = channel.unary_unary(
                '/esb.agent.v1.AgentService/ResumeContainer',
                request_serializer=agent__pb2.ResumeContainerRequest.SerializeToString,
                response_deserializer=agent__pb2.ResumeContainerResponse.FromString,
                _registered_method=True)
        self.ListContainers = channel.unary_unary(
                '/esb.agent.v1.AgentService/ListContainers',
                request_serializer=agent__pb2.ListContainersRequest.SerializeToString,
                response_deserializer=agent__pb2.ListContainersResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnsureContainer(self, request, context):
        """コンテナを確保し、接続情報を返す (なければ起動、あれば再利用)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyContainer(self, request, context):
        """明示的にコンテナを停止・削除する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseContainer(self, request, context):
        """コンテナを一時停止する (Warm Start 用)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeContainer(self, request, context):
        """コンテナを再開する (Warm Start 用)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContainers(self, request, context):
        """管理下の全コンテナの状態を取得 (Phase 3: Janitor 用)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnsureContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureContainer,
                    request_deserializer=agent__pb2.EnsureContainerRequest.FromString,
                    response_serializer=agent__pb2.WorkerInfo.SerializeToString,
            ),
            'DestroyContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyContainer,
                    request_deserializer=agent__pb2.DestroyContainerRequest.FromString,
                    response_serializer=agent__pb2.DestroyContainerResponse.SerializeToString,
            ),
            'PauseContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseContainer,
                    request_deserializer=agent__pb2.PauseContainerRequest.FromString,
                    response_serializer=agent__pb2.PauseContainerResponse.SerializeToString,
            ),
            'ResumeContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeContainer,
                    request_deserializer=agent__pb2.ResumeContainerRequest.FromString,
                    response_serializer=agent__pb2.ResumeContainerResponse.SerializeToString,
            ),
            'ListContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContainers,
                    request_deserializer=agent__pb2.ListContainersRequest.FromString,
                    response_serializer=agent__pb2.ListContainersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'esb.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('esb.agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnsureContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esb.agent.v1.AgentService/EnsureContainer',
            agent__pb2.EnsureContainerRequest.SerializeToString,
            agent__pb2.WorkerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esb.agent.v1.AgentService/DestroyContainer',
            agent__pb2.DestroyContainerRequest.SerializeToString,
            agent__pb2.DestroyContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esb.agent.v1.AgentService/PauseContainer',
            agent__pb2.PauseContainerRequest.SerializeToString,
            agent__pb2.PauseContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esb.agent.v1.AgentService/ResumeContainer',
            agent__pb2.ResumeContainerRequest.SerializeToString,
            agent__pb2.ResumeContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esb.agent.v1.AgentService/ListContainers',
            agent__pb2.ListContainersRequest.SerializeToString,
            agent__pb2.ListContainersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
